version: 2

jobs:
  build:
    working_directory: ~/circleci-python
    docker:
      - image: iandriley/todo:prod
    steps:
      - checkout
      - run: pip install poetry
      - run: poetry install
      - run: pip install gunicorn
      - run: pip install flask
      - run: poetry run gunicorn --bind 0.0.0.0:5000 todo_app.app:create_app()